Project/accounts/urls.py
# accounts/urls.py
from django.urls import path
from .views import register, profile
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', profile, name='profile'),
]

Project/catalog/urls.py
from django.urls import path
from .views import MainPageView, CategoryListView, BrandListView, KeyListView, KeyDetailView, add_to_cart, remove_from_cart, cart_detail, create_order, order_detail, confirm_order

urlpatterns = [
    path('', MainPageView.as_view(), name='main_page'),
    path('catalog/', CategoryListView.as_view(), name='category_list'),
    path('catalog/<int:category_id>/', BrandListView.as_view(), name='brand_list'),
    path('catalog/<int:category_id>/<int:brand_id>/', KeyListView.as_view(), name='key_list'),
    path('catalog/<int:category_id>/<int:brand_id>/<int:key_id>/', KeyDetailView.as_view(), name='key_detail'),
    path('cart/', cart_detail, name='cart_detail'),
    path('cart/add/<int:key_id>/', add_to_cart, name='add_to_cart'),
    path('cart/remove/<int:item_id>/', remove_from_cart, name='remove_from_cart'),
    path('order/create/', create_order, name='create_order'),
    path('order/<int:order_id>/', order_detail, name='order_detail'),
    path('order/<int:order_id>/confirm/', confirm_order, name='confirm_order'),
]

Project/homework_08/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('catalog.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project/accounts/models.py
from django.db import models

# Create your models here.

Project/catalog/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=200)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='children', blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "categories"

class Brand(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='assetc/images/brand/')

    def __str__(self):
        return self.name

class Key(models.Model):
    name = models.CharField(max_length=200)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    stock = models.PositiveIntegerField()
    image = models.ImageField(upload_to='assetc/images/keys/')

    def __str__(self):
        return self.name



class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    is_confirmed = models.BooleanField(default=False)

    def __str__(self):
        return f'Order {self.id} by {self.user.username}'

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    key = models.ForeignKey(Key, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return f'{self.quantity} of {self.key.name}'

class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'Cart of {self.user.username}'

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    key = models.ForeignKey(Key, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f'{self.quantity} of {self.key.name}'

Project/accounts/forms.py
# accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

Project/accounts/views.py
# accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from .forms import UserRegistrationForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from catalog.models import Order

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('main_page')
    else:
        form = UserRegistrationForm()
    return render(request, 'accounts/register.html', {'form': form})


@login_required
def profile(request):
    user_orders = Order.objects.filter(user=request.user)
    return render(request, 'accounts/profile.html', {'user_orders': user_orders})

Project/accounts/templates/accounts/login.html
{% load translate_errors %}


<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Авторизация</title>
    <!-- Подключение Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Магазин ключей для авто</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'category_list' %}">Каталог</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cart_detail' %}">Корзина</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Войти</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container mt-5">
        <h2>Авторизация</h2>
        <form method="post" class="mt-4">
            {% csrf_token %}
            {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                    <ul>
                        {% for field in form %}
                            {% for error in field.errors %}
                                <li>{{ error|translate_error }}</li>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <li>{{ error|translate_error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            <div class="form-group">
                {{ form.username.label_tag }}
                {{ form.username }}
            </div>
            <div class="form-group">
                {{ form.password.label_tag }}
                {{ form.password }}
            </div>
            <button type="submit" class="btn btn-primary">Войти</button>
        </form>
        <div class="mt-3">
            <a href="{% url 'register' %}" class="btn btn-secondary">Регистрация</a>
        </div>
    </div>

    <!-- Подключение Bootstrap JS и зависимостей -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

Project/accounts/templates/accounts/profile.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Профиль пользователя</title>
    <!-- Подключение Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Магазин ключей для авто</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'category_list' %}">Каталог</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cart_detail' %}">Корзина</a>
                </li>
                <li class="nav-item">
                    <form method="post" action="{% url 'logout' %}" style="display: inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-link nav-link">Выйти</button>
                    </form>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container mt-5">
        <h1>Профиль пользователя</h1>
        <h2>Заказы</h2>
        <ul class="list-group">
            {% for order in user_orders %}
                <li class="list-group-item">
                    Заказ №{{ order.id }} - Дата создания: {{ order.created_at }} - Подтвержден: {{ order.is_confirmed }}
                    <ul class="list-group mt-2">
                        {% for item in order.orderitem_set.all %}
                            <li class="list-group-item">{{ item.quantity }} x {{ item.key.name }}</li>
                        {% endfor %}
                    </ul>
                </li>
            {% empty %}
                <li class="list-group-item">Заказов пока нет.</li>
            {% endfor %}
        </ul>
    </div>

    <!-- Подключение Bootstrap JS и зависимостей -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

Project/accounts/templates/accounts/register.html
{% load translate_errors %}


<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Регистрация</title>
    <!-- Подключение Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Магазин ключей для авто</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'category_list' %}">Каталог</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cart_detail' %}">Корзина</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Войти</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container mt-5">
        <h1>Регистрация</h1>
        <form method="post" class="mt-4">
            {% csrf_token %}
            {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                    <ul>
                        {% for field in form %}
                            {% for error in field.errors %}
                                <li>{{ error|translate_error }}</li>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <li>{{ error|translate_error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            <div class="form-group">
                {{ form.username.label_tag }}
                {{ form.username }}
            </div>
            <div class="form-group">
                {{ form.email.label_tag }}
                {{ form.email }}
            </div>
            <div class="form-group">
                {{ form.password1.label_tag }}
                {{ form.password1 }}
            </div>
            <div class="form-group">
                {{ form.password2.label_tag }}
                {{ form.password2 }}
            </div>
            <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
        </form>
        <div class="mt-3">
            <a href="{% url 'login' %}" class="btn btn-secondary">Уже есть аккаунт? Войти</a>
        </div>
    </div>

    <!-- Подключение Bootstrap JS и зависимостей -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>